### ISSUE TITLE
`PoseSolver` only uses `NormalizeLandmark` for solving

### ISSUE THREAD

**Issue by seastar105** [vignetteapp/Moetion#14]
In kalidokit, PoseSolver is using WorldLandmark and NormalizedLandmark both. 

https://github.com/yeemachine/kalidokit/blob/c720d483df867996be96e2c3218e963da9190ecf/src/PoseSolver/index.ts#L15-L26

https://github.com/yeemachine/kalidokit/blob/c720d483df867996be96e2c3218e963da9190ecf/docs/script.js#L170-L173

Is there any reason only using NormalizedLandmark in Moetion here?

**Comment by Speykious** [comment]
Actually there isn't. When I read the code, I thought they were supposed to be the same kinds of coordinates, especially with this documentation comment:
```cs
    /**
     * Combines arm, hips, and leg calcs into one method
     * @param {Array} lm3d : array of 3D pose vectors from tfjs or mediapipe
     * @param {Array} lm2d : array of 2D pose vectors from tfjs or mediapipe
     * @param {String} runtime: set as either "tfjs" or "mediapipe"
     * @param {IPoseSolveOptions} options: options object
     */
```
Guess that's something to fix!
