### ISSUE TITLE
The result is different with Unity.Anagle Method?

### ISSUE THREAD

**Issue by Justin-sky** [vignetteapp/Moetion#18]
var v1 = new Vector3(0, 1, 0);
    var v2 = new Vector3(1, 0, 0);
    var angle = v1.FindRotation(v2) * Mathf.Rad2Deg;
    Debug.Log(angle);  // (28.65, -28.65, -14.32)

    var a2 = Vector3.Angle(v1, v2);
    Debug.Log(a2);  // 90

Is this result correct ?

**Comment by sr229** [comment]
This is a Unity side issue. Keep in mind we are 1:1 with Kalidokit so of it doesn't work there it won't work here. Please see #11 as well.
