### ISSUE TITLE
MediaPipeUnityPlugin Usage

### ISSUE THREAD

**Issue by BrandonBartram98** [vignetteapp/Moetion#9]
It it possible to use this alongside the tracking data from Holistic in the [MP Unity Plugin](https://github.com/homuler/MediaPipeUnityPlugin) to drive a 3D avatar e.g. readyplayerme rig body + face blendshapes?

If so, any advice on how to go about this would be appreciated.

**Comment by Speykious** [comment]
Moetion uses MediaPipe.NET, which is our .NET 6 port of MediaPipeUnityPlugin. So as it currently stands, you cannot use Moetion fresh from its latest Nuget package with MediaPipeUnityPlugin. Though it is probably possible to make a fork of it and replace the types used.

**Comment by Speykious** [comment]
Moetion uses MediaPipe.NET, which is our .NET 6 port of MediaPipeUnityPlugin. So as it currently stands, you cannot use Moetion fresh from its latest Nuget package with MediaPipeUnityPlugin. Though it is probably possible to make a fork of it and replace the types used.

**Comment by BrandonBartram98** [comment]
Great, thanks both!
